"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _ventas_tabla from './ventas-tabla.bones.json'
import _cotizaciones_tabla from './cotizaciones-tabla.bones.json'
import _productos_tabla from './productos-tabla.bones.json'
import _proveedores_tabla from './proveedores-tabla.bones.json'
import _gastos_tabla from './gastos-tabla.bones.json'
import _descuentos_tabla from './descuentos-tabla.bones.json'
import _laboratorio_tabla from './laboratorio-tabla.bones.json'
import _caja_historial_tabla from './caja-historial-tabla.bones.json'
import _empleados_tabla from './empleados-tabla.bones.json'
import _sueldos_tabla from './sueldos-tabla.bones.json'
import _asistencia_equipo_tabla from './asistencia-equipo-tabla.bones.json'
import _sucursales_tabla from './sucursales-tabla.bones.json'
import _roles_tabla from './roles-tabla.bones.json'
import _informes_libro_tabla from './informes-libro-tabla.bones.json'
import _dashboard_stats from './dashboard-stats.bones.json'
import _dashboard_accesos_rapidos from './dashboard-accesos-rapidos.bones.json'

configureBoneyard({"color":"#e2e8f0","darkColor":"#1e293b","animate":"shimmer","shimmerColor":"#f1f5f9","darkShimmerColor":"#334155","speed":"1.8s","shimmerAngle":110,"transition":true})

registerBones({
  "ventas-tabla": _ventas_tabla,
  "cotizaciones-tabla": _cotizaciones_tabla,
  "productos-tabla": _productos_tabla,
  "proveedores-tabla": _proveedores_tabla,
  "gastos-tabla": _gastos_tabla,
  "descuentos-tabla": _descuentos_tabla,
  "laboratorio-tabla": _laboratorio_tabla,
  "caja-historial-tabla": _caja_historial_tabla,
  "empleados-tabla": _empleados_tabla,
  "sueldos-tabla": _sueldos_tabla,
  "asistencia-equipo-tabla": _asistencia_equipo_tabla,
  "sucursales-tabla": _sucursales_tabla,
  "roles-tabla": _roles_tabla,
  "informes-libro-tabla": _informes_libro_tabla,
  "dashboard-stats": _dashboard_stats,
  "dashboard-accesos-rapidos": _dashboard_accesos_rapidos,
})
